### ISSUE TITLE
Message output

### ISSUE THREAD

**Issue by eljeffeg** [perfaram/pdf-zip-nes-polyglot#1]
I can't seem to get `--message` to work how I thought it might work.  It embeds it, but it just gets lost.  Doing a cat at the terminal spits out the entire thing as it normally would.  Strings also produces a slew of text.  A hex editor formatting makes it difficult to read.  So I'm trying to understand if it's broken or just not particularly useful.  Would be better to just append it to the end in such a case maybe were it could be read easily with cat / strings.  I sort of expected that under different conditions or commands, it might behave differently, similar to running it as a nes or opening it as a pdf.

Thanks for creating the example btw.

**Comment by perfaram** [comment]
You're right that the message "gets lost" in the middle of the resulting file.
I understand why it may not be desirable. I'd have to check, but I think that the reason was that appending the message at the end would corrupt the PDF file, while prepending it at the very beginning would make the whole file an invalid ZIP archive. On the other hand, the ZIP file can be "sparse" enough to accommodate for the message appearing between compressed/embedded files. 

As for providing a solution to your problem:
- You can do a binary search for a word that's in your message to find its offset,
- You search for "tail -f", because the script prepends your message with a command to output specifically your message (see README),
- You can edit the script to print out the offset of the message so it's easy for you to find it.

But there's no easy way to find it, save for searching the whole file, if you don't know the message offset, for the reasons outlined above.

**Comment by eljeffeg** [comment]
Forgot to mention that it wouldn't work in Chrome.  Not sure if that was due to size or something else, but it said format error.
